
  spring:
    application:
      name: ahadith
    profiles:
     active: ${SPRING_PROFILES_ACTIVE:dev}
  server:
     port: ${PORT:8080}

  jwt:
    secret: ${JWT_SECRET:9a4f2c8d3b7a1e5f6g0h9i8j7k6l5m4n3o2p1q0r9s8t7u6v5w4x3y2z1a0b1c2d3e4f5g6h7i8j9k0l1m2n3o4p5q6r7s8t9u0v1w2x3y4z5a6b7c8d9e0f}
    expiration: ${JWT_EXPIRATION:3600}
    refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800}